### ISSUE TITLE
API - Appointment model travel time

### ISSUE THREAD

**Issue by amayers** [workpathco/support#2]
`Appointment` models should have a `travel_time` property that is the # of minutes it should take to travel from the provided lat/lon to the appointment's location.

When fetching multiple `Appointments` we are already passing the lat/lon via the URL on the search request so no change would be required there.

When fetching a single `Appointment` we would need to support passing (optional) lat/lon via the URL.

**Comment by ghost** [comment]
You are right, travel time is on my list of things to add to the appointment object.  For the lat/lon that we use for the calculation, I was going to default to using the last known GPS coordinates for the user, since the app is going to be sending those in to us every few minutes.  But if you want to pass them in I can add params for that to GET /appointments/id

**Comment by amayers** [comment]
If it's not too much work I'd like to be able to send them with the request, but if a request doesn't then you would use the last known ones.

That way if the updated location hasn't been uploaded quite yet, we are still covered.

**Comment by amayers** [comment]
Oh, could we have both the travel time from the last `lat/lon` & from the home address?

**Comment by ghost** [comment]
I think we have settled this now, so I'm going to close out.
