### ISSUE TITLE
Appointment detail response does not include location

### ISSUE THREAD

**Issue by amayers** [workpathco/support#20]
The appointment detail call `/appointments/1004` does not have a `location` property in the response. However a call to `/appointments` and looking at appointment 1004 does have a `location`.

@hpainter

**Comment by ghost** [comment]
Boy this one turned out to be a bear.  It was only happening on the demo server, and eventually I tracked it down to where a passed reference to the appointment model was being used elsewhere and clobbering the original data.  I still am not entirely sure which JS VM is in the wrong (it should work or not work the same way everywhere), but I'm inclined to blame my Mac.

TL;DR: fixed now.
